
import java.util.HashMap;


public class MapGenres extends HashMap{
	public MapGenres(){
		super();
		put(0,"Blues");
		put(1,"Classic rock");
		put(2,"Country");
		put(3,"Dance");
		put(4,"Disco");
		put(5,"Funk");
		put(6,"Grunge");
		put(7,"Hip-Hop");
		put(8,"Jazz");
		put(9,"Metal");
		put(10,"New Age");
		put(11,"Oldies (rétro)");
		put(12,"Autre");
		put(13,"pop");
		put(14,"R'n'B");
		put(15,"Rap");
		put(16,"Reggae");
		put(17,"Rock");
		put(18,"Techno");
		put(19,"Industrial");
		put(20,"Alternative (rock alternatif)");
		put(21,"Ska");
		put(22,"Death metal");
		put(23,"Pranks");
		put(24,"Musique de film");
		put(25,"Euro-Techno");
		put(26,"Ambient");
		put(27,"Trip-hop");
		put(28,"Vocal");
		put(29,"Jazz-Funk");
		put(30,"Fusion");
		put(31,"Trance");
		put(32,"Classical (musique classique)");
		put(33,"Instrumental");
		put(34,"Acid");
		put(35,"House");
		put(36,"Musique de jeu vidéo");
		put(37,"Sound Clip (extrait sonore ou sample)");
		put(38,"Gospel");
		put(39,"Noise");
		put(40,"Rock alternatif");
		put(41,"Bass");
		put(42,"Soul");
		put(43,"Punk");
		put(44,"Space");
		put(45,"Meditative");
		put(46,"Pop instrumental");
		put(47,"Rock instrumental");
		put(48,"Musique ethnique");
		put(49,"Gothique");
		put(50,"Darkwave");
		put(51,"Techno-Industrial");
		put(52,"Musique électronique");
		put(53,"Pop-Folk");
		put(54,"Eurodance");
		put(55,"Dream");
		put(56,"Southern Rock (Rock sudiste)");
		put(57,"Comédie");
		put(58,"Cult (morceau \"culte\")");
		put(59,"Gangsta");
		put(60,"Top 40 (hits)");
		put(61 ,"Christian Rap (rap chrétien)");
		put(62,"Pop/Funk");
		put(63 ,"Jungle");
		put(64 ,"Musique indienne");
		put(65 ,"Cabaret");
		put(66 ,"New wave");
		put(67,"Psychédélique");
		put(68,"Rave");
		put(69,"Showtunes (comédie musicale ??? générique plutôt non ?)");
		put(70,"Bande-annonce");
		put(71 ,"Lo-fi");
		put(72 ,"Musique tribale");
		put(73 ,"Acid Punk");
		put(74 ,"Acid Jazz");
		put(75 ,"Polka");
		put(76 ,"Rétro");
		put(77 ,"Théâtre");
		put(78 ,"Rock & Roll");
		put(79 ,"Hard Rock");
		put(80 ,"Folk");
		put(81 ,"Folk rock");
		put(82,"National Folk (Folk américain)");
		put(83 ,"Swing");
		put(84 ,"Fast Fusion");
		put(85 ,"Bebop");
		put(86,"Latin (musique latine)");
		put(87 ,"Revival");
		put(88 ,"Musique celtique");
		put(89 ,"Bluegrass");
		put(90 ,"Avantgarde");
		put(91 ,"Gothic Rock");
		put(92 ,"Progressive Rock (Rock progressif)");
		put(93 ,"Psychedelic Rock (Rock psychédélique)");
		put(94 ,"Symphonic Rock (Rock symphonique)");
		put(95 ,"Slow Rock");
		put(96,"Big Band");
		put(97 ,"Chœur");
		put(98 ,"Easy listening");
		put(99 ,"Acoustic (Acoustique)");
		put(100 ,"Humour");
		put(101 ,"Speech (discours)");
		put(102 ,"Chanson");
		put(103 ,"Opéra");
		put(104 ,"Musique de chambre");
		put(105 ,"Sonata (Sonate)");
		put(106 ,"Symphonie");
		put(107 ,"Booty Bass");
		put(108,"Primus");
		put(109,"Porn groove");
		put(110,"Satire");
		put(111,"Slow Jam");
		put(112,"Club");
		put(113,"Tango");
		put(114,"Samba");
		put(115,"Folklore");
		put(116,"Ballad (ballade)");
		put(117,"Power ballad");
		put(118,"Rythmic soul");
		put(119,"Freestyle");
		put(120,"Duet (duo)");
		put(121,"Punk rock");
		put(122,"Drum Solo (solo de batterie)");
		put(123,"A cappella");
		put(124,"Euro-house");
		put(125,"Dancehall");
		put(126,"Goa");
		put(127,"Drum and bass");
		put(128,"Club House");
		put(129,"Hardcore");
		put(130,"Terror");
		put(131,"Indie");
		put(132,"BritPop");
		put(133,"Negerpunk");
		put(134,"Polsk Punk");
		put(135,"Beat");
		put(136,"Christian gangsta rap");
		put(137,"Heavy metal");
		put(138,"Black metal");
		put(139,"Crossover");
		put(140,"Musique chrétienne contemporaine");
		put(141,"Rock chrétien");
		put(142,"Merengue");
		put(143,"Salsa");
		put(144,"Thrash metal");
		put(145,"Anime");
		put(146,"JPop");
		put(147,"Synthpop");
	}
} 
